import {
  ArrowRightLeft,
  BoxesIcon,
  Building2,
  CircleDollarSign,
  ClipboardList,
  FileImageIcon,
  Footprints,
  LayoutTemplate,
  type LucideProps,
  Mail,
  Menu,
  Package,
  PackageSearch,
  PanelsTopLeft,
  RssIcon,
  Search,
  SendIcon,
  Settings,
  ShieldIcon,
  Sliders,
  SlidersHorizontal,
  Star,
  TagIcon,
  Tags,
  TextCursorInput,
  TruckIcon,
  UserCheck,
  UsersRound,
} from "lucide-react";
import { type ExoticComponent } from "react";

type ExtraNavKeys = "websites/create";
type NavKey = string | ExtraNavKeys;

export const navIconMap: Partial<Record<NavKey, ExoticComponent<LucideProps>>> = {
  redirects: ArrowRightLeft,
  forms: TextCursorInput,
  "form-submissions": SendIcon,
  search: Search,
  administrators: ShieldIcon,
  roles: UserCheck,
  permission: ShieldIcon,
  pages: LayoutTemplate,
  posts: RssIcon,
  media: FileImageIcon,
  categories: TagIcon,
  header: Menu,
  footer: Footprints,
  customers: UsersRound,
  orders: ClipboardList,
  fulfilment: Building2,
  products: PackageSearch,
  productCategories: TagIcon,
  productSubCategories: Tags,
  productReviews: Star,
  emailMessages: Mail,
  shopSettings: Settings,
  shopLayout: PanelsTopLeft,
  "inpost-courier-cod": TruckIcon,
  "inpost-courier": TruckIcon,
  "inpost-pickup": BoxesIcon,
  payment: CircleDollarSign,
  "websites/create": LayoutTemplate,
  productsnew: Package,
  attributes: Sliders,
  "shop-configuration": SlidersHorizontal,
};

export const getNavIcon = (slug: string) =>
  Object.hasOwn(navIconMap, slug) ? navIconMap[slug] : undefined;
